# Start: Enable SSL on localhost
server:
  ssl:
    keystore: 
      location: ${server.ssl.keystore}
      password: ${server.ssl.password}
      type: pkcs12

    key:
      password: ${server.ssl.password}

    truststore: 
      location: ${server.ssl.keystore}
      password: ${server.ssl.password}
      type: PKCS12
    
    # Enable client certificate authentication for certificate-bound tokens
    client-auth: want
# End: Enable SSL on localhost
