# Start: Enable SSL on localhost
server:
  ssl:
    keystore: 
      location: classpath:dev.localhost.com.p12
      password: ${server.ssl.password}
      type: pkcs12

    key:
      password: ${server.ssl.password}

    truststore: 
      location: classpath:dev.localhost.com.p12
      password: ${server.ssl.password}
      type: PKCS12
# End: Enable SSL on localhost
