# Start: Enable SSL on localhost
server:
  ssl:
    key-store: ${server.ssl.keystore} #classpath:dev.localhost.com.p12
    key-store-password: ${server.ssl.password}
    key-store-type: pkcs12
    key-password: ${server.ssl.password}
# End: Enable SSL on localhost
